<?php

namespace AppBundle\Repository;

/**
 * TDPersonRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TDPersonRepository extends \Doctrine\ORM\EntityRepository
{  
}
